version: '3'

services:
  frontend:
    build: ./client
    container_name: auth-client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - authentication-network

  backend:
    build: .
    container_name: auth-back
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - authentication-network

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - authentication-network

volumes:
  mongo-data:
    

networks:
  authentication-network:
    driver: bridge
