version: '3'

services:
  frontend:
    build: ./client  
    container_name: auth-client
    ports:
      - "80:80"  
    depends_on:
      - backend 
    networks:
      -authentication-network


  backend:
    build: Dockerfile 
    container_name: auth-back
    ports:
      - "3000:3000" 
    depends_on:
      - database
    networks:
       -authentication-network 

   

  database:
    image: mongo
    container_name: mongo-db 
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db
    networks:
      -authentication-network  

networks:
  authentication-network:
    driver: bridge  
