version: '3'

services:
  backend:
    build:
      context: ./api  
    ports:
      - "3000:3000"  
    environment:
      - MONGODB_URI=mongodb://mongo:27017/authentication 
    depends_on:
      - mongo  

  frontend:
    build:
      context: ./client  
    ports:
      - "80:80"  
    depends_on:
      - backend  

  mongo:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:  
